language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - chmod +x mvnw
script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)

