language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - mvn cobertura:cobertura coveralls:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report

